services:
  - type: web
    name: discord-bot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: MONGODB_URL
        sync: false
      - key: TOKEN
        sync: false
      - key: PORT
        value: "10000"  # Set the port explicitly


