services:
  - type: web
    name: UltimateBot
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
      python bot.py
    envVars:
      - key: TOKEN
        sync: false  # Add manually in Render's environment settings
      - key: PORT
        value: "10000"
